#!/usr/bin/bash

live_mount(){
    mkdir -p /donkey/a # upper
    mkdir -p /donkey/b # workdir
    mkdir -p /live_root/
    mkdir -p /new_root/
    mkdir -p /source/ # lower
    mount $root /new_root/ 2> /dev/null
    mount /new_root/live/airootfs.sfs /source/ 2> /dev/null
    mount -t overlay -o lowerdir=/source/,upperdir=/donkey/a/,workdir=/donkey/b overlay /live_root
    mount -t tmpfs -o size=100% none /donkey/a
    mount -t tmpfs -o size=100% none /donkey/b
    [ -d /source/merge/ ] && cp -prfv /source/merge/* /live_root/
    mount --bind /live_root /new_root/
    mkdir /new_root/cdrom/ 2> /dev/null
    mkdir /new_root/source/ 2> /dev/null
    mount $root /new_root/cdrom/ 2> /dev/null
    mount /new_root/cdrom/live/airootfs.sfs /new_root/source/ 2> /dev/null
}
is_file_avaiable(){
    disktmp=$(mktemp)
    rm -f $disktmp
    mkdir -p $disktmp || true
    timeout 10 mount -t auto "$1" $disktmp &>/dev/null
    [ -f "$disktmp/$2" ] && [ -b "$1" ]
    status=$?
    umount -lf $disktmp 2>/dev/null
    return $status
}

run_hook() {
    # live-boot
    if cat /proc/cmdline | grep "boot=live" >/dev/null ; then
    while [ "$root" == "" ] ; do
		list=$(ls /sys/class/block/ | grep ".*[0-9]$" | grep -v loop | grep -v ram | grep -v nbd | grep -v fd | sed "s|^|/dev/|g")
		for part in $list
		do
			sleep 0.1
			echo "Looking for: $part"
			if is_file_avaiable "$part" "/live/airootfs.sfs"
			then
				export root=$part
			fi
		done
	done
    export mount_handler="live_mount"
    fi
}
run_latehook(){
    # live-config 
    if ! cat /proc/cmdline | grep "init=" ; then
        export init=/sbin/init
    fi
    if cat /proc/cmdline | grep -E "boot=live|live-config" >/dev/null ; then
        for i in $(cat /proc/cmdline)
        do
            export $i &>/dev/null || true
        done
        if [ "${live_user}" == "" ] ; then
            export live_user="user"
        fi
        if [ "${live_pass}" == "" ] ; then
            export live_pass="live"
        fi
        if [ "${live_hostname}" == "" ] ; then
            export live_hostname="teaiso"
        fi
        chroot /new_root/ sh -c "useradd -m ${live_user} -s /bin/bash -p UttMT5OhD7chw -U" || true
        for i in log network floppy scanner power rfkill users storage optical audio wheel adm ; do
            chroot /new_root/ sh -c "usermod -aG $i ${live_user}" || true
        done

	chroot /new_root/ sh -c "groupadd -r autologin && gpasswd -a user autologin && groupadd -r nopasswdlogin && gpasswd -a user nopasswdlogin" || true
        chroot /new_root/ sh -c "echo -ne \"${live_pass}\\n${live_pass}\\n\" | passwd ${live_user}" || true
        chroot /new_root/ sh -c "echo -ne \"${live_pass}\\n${live_pass}\\n\" | passwd" || true
        echo ${live_hostname} > /new_root/etc/hostname || true
    fi
    # This is bruh moment (debug timeout)
    echo -en "\033c"
    echo " _                _  "     
    echo "| |              | |    " 
    echo "| |__  _ __ _   _| |__  "
    echo "| '_ \| '__| | | | '_ \ "
    echo "| |_) | |  | |_| | | | |"
    echo "|_.__/|_|   \__,_|_| |_|"
    sleep 0.3
}
